env:
  es6: true
parserOptions:
  ecmaVersion: 10
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - prettier
rules:
  prettier/prettier: error
extends:
  - 'plugin:prettier/recommended'
